import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Footer } from "./components/layout/Footer";
import { LenisProvider } from "./providers/LenisProvider";

export const neueRegrade = localFont({
  src: "./fonts/neue_regrade_variable.ttf",
  variable: "--font-neue-regrade",
  display: "swap",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${neueRegrade.variable} antialiased`}>
      <body>
        <LenisProvider>
          {children}
          <Footer />
        </LenisProvider>

      </body>
    </html>
  );
}
